// src/components/custom/users/control/form/auto-generated-fields.tsx
import React from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

interface AutoGeneratedFieldsProps {
    mode: 'create' | 'edit'
}

export const AutoGeneratedFields: React.FC<AutoGeneratedFieldsProps> = ({ mode }) => (
    <Card>
        <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium">
                <p className="text-sm text-gray-500">
                    Note: The following will be automatically {mode === 'create' ? 'generated' : 'updated'}:
                </p>
            </CardTitle>
        </CardHeader>
        <CardContent>
            <ul className="text-sm text-gray-500 list-disc list-inside">
                {mode === 'create' ? (
                    <>
                        <li>User ID</li>
                        <li>Username (from email)</li>
                        <li>Created At</li>
                        <li>Updated At</li>
                        <li>Active Status</li>
                    </>
                ) : (
                    <li>Updated At</li>
                )}
            </ul>
        </CardContent>
    </Card>
)